# All messages can contain standard chat color features and HEX Colors

# DeathHolding.Clear:
#  description: Allows the user to clear all DeathHolding armor stands from the world.
# DeathHolding.Reload:
#  description: Allows the user to reload this plugins config.yml
# DeathHolding.Give:
#  description: Allows the user to give themselves or another user a revival item.
# DeathHolding.Revive:
#  description: Bypass the revival stage of this plugin.
# DeathHolding.Bypass:
#  description: Needed in order to be able to revive another player.
# DeathHolding.Cooldown.Bypass:
#  description: Needed in ordet to bypass the cooldown timer.

Permissions:
  # If this is true, permissions will be required
  usePermissions: false

NoPermission:
  ConsoleMessage:
    Message:
      - "&8---------------------------"
      - "&cMissing Permission"
      - "&ePlayer &8» &f%PlayerName%"
      - "&ePermission &8» &f%MissingPermission%"
      - "&8---------------------------"
  Player:
    Message:
      - "&cMissing Permission &8» &c%MissingPermission%"

Revival:
  # The Health a player should have when revived
  Health: 6
  # The Sound played when a player is revived
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
  SoundEffects:
    Sound1: ENTITY_PLAYER_LEVELUP
  # The potion effect given to a player when revived
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
  PotionEffects:
    Effect1:
      Type: REGENERATION
      Duration: 5
      Strength: 2
    Effect2:
      Type: SPEED
      Duration: 3
      Strengt: 10
  Item:
    isCustom: false
    # If isCustom is set to false, custom-item will be ignored and the default-item will be used.
    # You can use the command /revival give %target% %amount% to spawn in a custom revival item
    custom-item:
      type: GOLDEN_CARROT
      displayName: "&a&lREVIVAL APPLE"
      lore:
        - " "
        - "&7&oRight-Click Someone to revive them"
      isEnchanted: true
    default-item: GOLDEN_APPLE
  Message:
    # The message sent to the user that REVIVED someone
    toReviver:
      - "You revived %target_name%"
    # The message sent to the user that WAS revived
    toTarget:
      - "You have been revived by %player_name%"
  # How long should a user have to wait before being able to revive someone
  Cooldown:
    Time: 30
    Message:
      - "Cooldown: %player_cooldown%"
Dying:
  # The title above a player when they are dying
  Title: "&8[&c&lDYING&8] &f%player_name%"
  # How long should a player be "dying" for (seconds)
  TimeToRevive: 60
  # The Health a player should have when they go into the dying state
  Health: 6
  # The Sound played when a player is put into the dying state
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
  SoundEffects:
    Sound1: ITEM_TOTEM_USE
  # The potion effect given to a player when revived
  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
  # Potion effects are removed if a player dies or is revived from the dying state.
  PotionEffects:
    Effect1:
      Type: BLINDNESS
      Duration: 60
      Strength: 100
