name: DeathHolding
version: '${project.version}'
main: me.akagiant.deathholding.Main
api-version: 1.18

softdepend: [PlaceholderAPI]

commands:
  dh:
    aliases:
      - DeathHolding

permissions:
  DeathHolding.*:
    description: All DeathHolding Permissions
    default: op
    children:
      DeathHolding.Revive: true
      DeathHolding.Bypass: true
      DeathHolding.Cooldown.Bypass: true
      DeathHolding.Reload: true
      DeathHolding.Give: true
      DeathHolding.Clear: true

  DeathHolding.Clear:
    description: Allows the user to clear all DeathHolding armor stands from the world.
  DeathHolding.Reload:
    description: Allows the user to reload this plugins config.yml
  DeathHolding.Give:
    description: Allows the user to give themselves or another user a revival item.
  DeathHolding.Revive:
    description: Bypass the revival stage of this plugin.
  DeathHolding.Bypass:
    description: Needed in order to be able to revive another player.
  DeathHolding.Cooldown.Bypass:
    description: Needed in ordet to bypass the cooldown timer.